version: '3.3'
services:
    fruiqi:
        image: hub.infervision.com/dev/fruiqi:dev-${BASE_IMAGE}
        restart: always
        build:
            context: .
            dockerfile: Dockerfile-dev
            args:
                BASE_IMAGE: ${BASE_IMAGE}
        tty: true
        environment:
            - TZ=Asia/Shanghai
            - EXTRACT_DATA_PATH=${DATA_PATH}
            - EXTRACT_REPACS_URL=http://${SERVER_IP}:${REPACS_PORT}/
        volumes:
            - ${DATA_PATH}:${DATA_PATH}
            - ./logs:/app/logs
            - ./bff:/app
            - ~/.ssh:/home/docker/.ssh
